#!/bin/bash

export bg=$(xrdb ~/.config/X11/xresources -query all | grep background | awk '{print $2}')
export fg=$(xrdb ~/.config/X11/xresources -query all | grep foreground | awk '{print $2}')

dunst -lb "$bg" -nb "$bg" -cb "$bg" -lf "$fg" -bf "$fg" -cf "$fg" -nf "$fg" -fn "Neep 8" -s -geometry "250x40-12+38" -format "<b>%s</b>\n%b" -separator_height 0 -key "ctrl+space" -all_key "space" -padding 22 -horizontal_padding 22
