#!/bin/sh

bg=$(xrdb ~/.config/X11/xresources -query all | grep background | awk '{print $2}')
$HOME/.config/polybar/launch.sh &
picom --config ~/.config/picom/picom.conf &
run_dunst &

bspc monitor -d term web code files media extra

bspc config focused_border_color   "#74838c"
bspc config normal_border_color     "$bg"
bspc config border_width            2
bspc config window_gap              12
bspc config focus_follows_pointer   true
bspc config top_padding             26
bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on

floating_noborder
